/*
 * Copyright (c) 2026 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * corner radius: 2
 */
export const CORNER_RADIUS_2: Resource = $r('sys.float.corner_radius_level1');

/**
 * corner radius: 4
 */
export const CORNER_RADIUS_4: Resource = $r('sys.float.corner_radius_level2');

/**
 * corner radius: 8
 */
export const CORNER_RADIUS_8: Resource = $r('sys.float.corner_radius_level4');

/**
 * corner radius: 12
 */
export const CORNER_RADIUS_12: Resource = $r('sys.float.corner_radius_level6');

/**
 * corner radius: 16
 */
export const CORNER_RADIUS_16: Resource = $r('sys.float.corner_radius_level8');

/**
 * corner radius: 20
 */
export const CORNER_RADIUS_20: Resource = $r('sys.float.corner_radius_level10');

/**
 * corner radius: 29
 */
export const CORNER_RADIUS_29: number = 29;

/**
 * corner radius: 32
 */
export const CORNER_RADIUS_32: Resource = $r('sys.float.corner_radius_level16');

/**
 * corner radius: 40
 */
export const CORNER_RADIUS_40: number = 40;