/*
 * Copyright (c) 2026 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * Padding: 0vp
 */
export const PADDING_0VP: number = 0;

/**
 * Padding: 2vp
 */
export const PADDING_2VP: number = 2;

/**
 * Padding: 3vp
 */
export const PADDING_3VP: number = 3;

/**
 * Padding: 4vp
 */
export const PADDING_4VP: number = 4;

/**
 * Padding: 5vp
 */
export const PADDING_5VP: number = 5;

/**
 * Padding: 6vp
 */
export const PADDING_6VP: number = 6;

/**
 * Padding: 8vp
 */
export const PADDING_8VP: number = 8;

/**
 * Padding: 10vp
 */
export const PADDING_10VP: number = 10;

/**
 * Padding: 11vp
 */
export const PADDING_11VP: number = 11;

/**
 * Padding: 12vp
 */
export const PADDING_12VP: number = 12;

/**
 * Padding: 14vp
 */
export const PADDING_14VP: number = 14;

/**
 * Padding: 16vp
 */
export const PADDING_16VP: number = 16;

/**
 * Padding: 18vp
 */
export const PADDING_18VP: number = 18;

/**
 * Padding: 20vp
 */
export const PADDING_20VP: number = 20;

/**
 * Padding: 22vp
 */
export const PADDING_22VP: number = 22;

/**
 * Padding: 24vp
 */
export const PADDING_24VP: number = 24;

/**
 * Padding: 26vp
 */
export const PADDING_26VP: number = 26;

/**
 * Padding: 28vp
 */
export const PADDING_28VP: number = 28;

/**
 * Padding: 32vp
 */
export const PADDING_32VP: number = 32;

/**
 * Padding: 36vp
 */
export const PADDING_36VP: number = 36;

/**
 * Padding: 40vp
 */
export const PADDING_40VP: number = 40;

/**
 * Padding: 42vp
 */
export const PADDING_42VP: number = 42;

/**
 * Padding: 48vp
 */
export const PADDING_48VP: number = 48;

/**
 * Padding: 50vp
 */
export const PADDING_50VP: number = 50;

/**
 * Padding: 64vp
 */
export const PADDING_64VP: number = 64;

/**
 * Padding: 80vp
 */
export const PADDING_80VP: number = 80;

/**
 * Padding: 160vp
 */
export const PADDING_160VP: number = 160;

