/*
 * Copyright (c) 2026 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/**
 * size: 1
 */
export const SIZE_NUM_1: number = 1;

/**
 * size: 6
 */
export const SIZE_NUM_6: number = 6;

/**
 * size: 10
 */
export const SIZE_NUM_10: number = 10;

/**
 * size: 12
 */
export const SIZE_NUM_12: number = 12;


/**
 * size: 14
 */
export const SIZE_NUM_14: number = 14;


/**
 * size: 15
 */
export const SIZE_NUM_15: number = 15;

/**
 * size: 16
 */
export const SIZE_NUM_16: number = 16;

/**
 * size: 19
 */
export const SIZE_NUM_19: number = 19;

/**
 * size: 20
 */
export const SIZE_NUM_20: number = 20;

/**
 * size: 24
 */
export const SIZE_NUM_24: number = 24;

/**
 * size: 26
 */
export const SIZE_NUM_26: number = 26;

/**
 * size: 28
 */
export const SIZE_NUM_28: number = 28;


/**
 * size: 34
 */
export const SIZE_NUM_34: number = 34;


/**
 * size: 35
 */
export const SIZE_NUM_35: number = 35;

/**
 * size: 36
 */
export const SIZE_NUM_36: number = 36;

/**
 * size: 40
 */
export const SIZE_NUM_40: number = 40;

/**
 * size: 48
 */
export const SIZE_NUM_48: number = 48;

/**
 * size: 56
 */
export const SIZE_NUM_56: number = 56;

/**
 * size: 58
 */
export const SIZE_NUM_58: number = 58;

/**
 * size: 60
 */
export const SIZE_NUM_60: number = 60;

/**
 * size: 63
 */
export const SIZE_NUM_63: number = 63;

/**
 * size: 64
 */
export const SIZE_NUM_64: number = 64;

/**
 * size: 65
 */
export const SIZE_NUM_65: number = 65;

/**
 * size: 66
 */
export const SIZE_NUM_66: number = 66;

/**
 * size: 72
 */
export const SIZE_NUM_72: number = 72;

/**
 * size: 76
 */
export const SIZE_NUM_76: number = 76;

/**
 * size: 77
 */
export const SIZE_NUM_77: number = 77;

/**
 * size: 80
 */
export const SIZE_NUM_80: number = 80;

/**
 * size: 81
 */
export const SIZE_NUM_81: number = 81;

/**
 * size: 83
 */
export const SIZE_NUM_83: number = 83;

/**
 * size: 86
 */
export const SIZE_NUM_86: number = 86;

/**
 * size: 88
 */
export const SIZE_NUM_88: number = 88;

/**
 * size: 90
 */
export const SIZE_NUM_90: number = 90;

/**
 * size: 91PX
 */
export const SIZE_91PX: string = '91px';

/**
 * size: 96
 */
export const SIZE_NUM_96: number = 96;

/**
 * size: 100
 */
export const SIZE_NUM_100: number = 100;

/**
 * size: 104
 */
export const SIZE_NUM_104: number = 104;

/**
 * size: 108
 */
export const SIZE_NUM_108: number = 108;

/**
 * size: 110
 */
export const SIZE_NUM_110: number = 110;

/**
 * size: 125px
 */
export const SIZE_125PX: string = '125px';

/**
 * size: 128
 */
export const SIZE_NUM_128: number = 128;

/**
 * size: 137
 */
export const SIZE_NUM_137: number = 137;

/**
 * size: 174PX
 */
export const SIZE_174PX: string = '174px';

/**
 * size: 188
 */
export const SIZE_NUM_188: number = 188;

/**
 * size: 200
 */
export const SIZE_NUM_200: number = 200;

/**
 * size: 208PX
 */
export const SIZE_208PX: string = '208px';

/**
 * size: 212
 */
export const SIZE_NUM_212: number = 212;

/**
 * size: 280
 */
export const SIZE_NUM_280: number = 280;

/**
 * size: 300
 */
export const SIZE_NUM_300: number = 300;

/**
 * size: 444
 */
export const SIZE_NUM_444: number = 444;

/**
 * size: 475
 */
export const SIZE_NUM_475: number = 475;

/**
 * size: 592
 */
export const SIZE_NUM_592: number = 592;

/**
 * size: 600
 */
export const SIZE_NUM_600: number = 600;

/**
 * size: 636
 */
export const SIZE_NUM_636: number = 636;

/**
 * size: '100%'
 */
export const SIZE_PERCENT_100: string = '100%';

/**
 * size: '40%'
 */
export const SIZE_PERCENT_40: string = '40%';

/**
 * size: '50%'
 */
export const SIZE_PERCENT_50: string = '50%';

/**
 * size: '60%'
 */
export const SIZE_PERCENT_60: string = '60%';

/**
 * size: '80%'
 */
export const SIZE_PERCENT_80: string = '80%';

/**
 * size: '700%'
 */
export const SIZE_PERCENT_700: string = '700%';