/*
 * Copyright (c) 2026 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * Spacing: 0vp
 */
export const SPACE_0: number = 0;

/**
 * Spacing: 1.5vp
 */
export const SPACE_1_POINT_5: number = 1.5;

/**
 * Spacing: 2vp
 */
export const SPACE_2: number = 2;

/**
 * Spacing: 4vp
 */
export const SPACE_4: number = 4;

/**
 * Spacing: 6vp
 */
export const SPACE_6: number = 6;

/**
 * Spacing: 8vp
 */
export const SPACE_8: number = 8;

/**
 * Spacing: 10vp
 */
export const SPACE_10: number = 10;

/**
 * Spacing: 12vp
 */
export const SPACE_12: number = 12;

/**
 * Spacing: 16vp
 */
export const SPACE_16: number = 16;

/**
 * Spacing: 24vp
 */
export const SPACE_24: number = 24;

/**
 * Spacing: 28vp
 */
export const SPACE_28: number = 28;


/**
 * Spacing: 30vp
 */
export const SPACE_30: number = 30;

/**
 * Spacing: 32vp
 */
export const SPACE_32: number = 32;
